settings:
  name: world n
  bannedPlayers: 
    - "ID1"
    - "ID2"
  bannedIPs: 
    - "0.0.0.0:5555"
    - "127.0.0.1:5555"
  seed: 123456789
  userID: "1234567890"
  address: "0.0.0.0:5555"
  type: "host"
  packages: ["worldspawn", "MYPACKAGE"]
  packageLinks:
    MYPACKAGE: "DOWNLOADLINK"
